import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/context'
import Navbar from './../components/Navbar/index';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'incridea',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
         
          <main className='flex  flex-col ' >{children}</main>
          <ToastContainer />
        </GlobalState>
      </body>
    </html>
  )
}
